### ISSUE TITLE
Need to specify API secret as bytes, this is undocumented and contrary to API specs

### ISSUE THREAD

**Issue by kjgd** [nlsdfnbch/hitbtc#10]
The HitBTC API [specifies](https://api.hitbtc.com/?shell#socket-session-authentication) that key and secret should be strings  but Python hmac requires it as bytes or bytearray, and it is not converted before sending it to the hmac module:

```
signature = hmac.new(secret, raw_sig, hashlib.sha256).hexdigest()
File "lib/python3.6/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
File "lib/python3.6/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```

**Comment by wuxuonline** [comment]
https://www.cnblogs.com/xiaoxiao-niao/p/8266768.html

**Comment by deepbrook** [comment]
Gets me every time. I'll fix this in the coming hours.

**Comment by kjgd** [comment]
I've tried encoding the secret [here](https://github.com/Crypto-toolbox/hitbtc/blob/fb0170beda7caba8dd3ff5a72aaa6021f1678ef5/hitbtc/connector.py#L210) using:

- secret.encode()
- secret.encode(encoding='UTF-8')
- secret.encode('utf-8')
- secret.encode('ascii')
- secret.encode('latin-1')

...and none of those resulted in a successful authentication.

I also tried removing the [already extant 'utf-8' encoding statement](https://github.com/Crypto-toolbox/hitbtc/blob/fb0170beda7caba8dd3ff5a72aaa6021f1678ef5/hitbtc/connector.py#L209) and trying to encode both secret and raw-sig with no parameters as well as using 'ascii' encoding on both... no luck there either!

I have also tried 2 different API key/secret pairs (and double checked their correctness)...

**Comment by deepbrook** [comment]
You should always specify an encoding,  just to be sure. 
However,  if neither of those fixes worked for you,  perhaps I need to review the signature generation.  I don't have api keys for hitbtc,  since  I usually only subscribe to market data. But as I said above,  I'll look into this today.

**Comment by deepbrook** [comment]
See if this last commit fixed it - if it didn't, it might be due to the `hexdigest()` call to the hmax signature, in which case calling `decode('utf8)` instead might be the solution.

**Comment by kjgd** [comment]
Works for me
