### ISSUE TITLE
Not handling login responses correctly

### ISSUE THREAD

**Issue by kjgd** [nlsdfnbch/hitbtc#13]
Request:
`{'method': 'login', 'params': {'sKey': 'XXXX', 'algo': 'BASIC', 'pKey': 'XXXX'}, 'id': 15166975643124}`

then we get a `<class 'TypeError'>` exception '`format() argument after ** must be a mapping, not bool`' trying to handle message `{'jsonrpc': '2.0', 'result': True, 'id': 15166984862827}`

**Comment by deepbrook** [comment]
Merged!
