### ISSUE TITLE
Not handling balance responses correctly

### ISSUE THREAD

**Issue by kjgd** [nlsdfnbch/hitbtc#14]
Requesting balances with 
`{'method': 'getTradingBalance', 'params': {}, 'id': 15166984862834}`
produces a `<class 'KeyError'>` exception '`'available'`' trying to handle message `{'jsonrpc': '2.0', 'result': [{'currency': '1ST', 'available': '0', 'reserved': '0'} (....) ], 'id': 15166984862834}`

**Comment by kjgd** [comment]
Scratching my head over this one... added some more debugging statements and got the following gem:
Formatter for method getTradingBalance failed on item `{'currency': 'ZSC', 'available': '0', 'reserved': '0'}` with KeyError '`available`'

**Comment by deepbrook** [comment]
mmkaaaaayy..print the keys, see what they say ?

**Comment by kjgd** [comment]
Formatter for method getTradingBalance failed on item `{'currency': 'ZSC', 'available': '0', 'reserved': '0'}` with KeyError '`available`'... item keys `dict_keys(['currency', 'available', 'reserved'])`

**Comment by deepbrook** [comment]
could be that it's looping over the wrong `dict` - perhaps over the response, instead of the dict in `response['result']`

**Comment by kjgd** [comment]
Here is the code with the debugging statement:
```
for item in response['result']:
    try:
        text += msg.format(item)
    except KeyError as e :
        print("Formatter for method {} failed on item {} with KeyError {}... item keys {}".format(method, item, e, item.keys()))
```
response['result'] is a list of the [following format](https://api.hitbtc.com/?shell#get-trading-balance):
```
[
    {
      "currency": "BCN",
      "available": "100.000000000",
      "reserved": "0"
    },
    {
      "currency": "BTC",
      "available": "0.013634021",
      "reserved": "0"
    }
  ],
```

**Comment by kjgd** [comment]
I tried updating the formatter as follows... before it had empty braces for wallet:
```
resp_get_trading_balance = 'Wallet: {}\n' \
                      '\tAvailable: {available}\n' \
                      '\tReserved: {reserved}\n'
```
This is actually not correct, we need to be getting the value from key 'currency' so I added:

```
resp_get_trading_balance = 'Wallet: {currency}\n' \
                      '\tAvailable: {available}\n' \
                      '\tReserved: {reserved}\n'
```

That just changed how early in the game we get an error:
`Formatter for method getTradingBalance failed on item {'currency': 'ZSC', 'available': '0', 'reserved': '0'} with KeyError 'currency'... item keys dict_keys(['currency', 'available', 'reserved'])`

**Comment by kjgd** [comment]
Fixed with:
`text += msg.format(**item)`
pull request incoming...

**Comment by deepbrook** [comment]
merged! Cheers!
