### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by marcioacmauricio** [nlsdfnbch/hitbtc#2]
Sorry, could you give an example?

**Comment by deepbrook** [comment]
@marcioacmauricio, of course! 👍 
I'll add an in-depth example to the Readme (sorry, I just uploaded this project yesterday!), but to get started try:

```python
from hitbtc import HitBTC
c = HitBTC()
c.start()
c.subscribe_ticker(symbol='ETHBTC')
# do stuff
...
c.stop()
```

**Comment by deepbrook** [comment]
added usage example to readme!

**Comment by marcioacmauricio** [comment]
thank you so much!
