### ISSUE TITLE
How to properly add key and api to params

### ISSUE THREAD

**Issue by yamontv** [nlsdfnbch/hitbtc#23]
Try with 1.0.4 and 1.0.5.dev0

```
import time
import queue
from hitbtc import HitBTC

c = HitBTC(key="abcd", secret="efgd")
c.start()  # start the websocket connection
time.sleep(2)  # Give the socket some time to connect
c.login()
```
Whats wrong with this? I got error TypeError: key: expected bytes or bytearray, but got 'str'
How to properly convert str for your lib?

try to change to:
`key="abcd".encode()`
And lib raise new error

**Comment by yamontv** [comment]
Ok. I found that bug only if I use: 
```
pip install hitbtc
pip install --pre hitbtc
```
When I download source from github and install with "pip install ." all work fine

**Comment by deepbrook** [comment]
Hey @yamontv ,
sorry for the slow reply.
Apologies for the stale version on pip! It's true that it's in need of updating. Unfortunately I'm quite busy atm, so this might be the case for a little while longer.
