### ISSUE TITLE
AttributeError: 'HitBTC' object has no attribute 'recv'

### ISSUE THREAD

**Issue by walidmujahid** [nlsdfnbch/hitbtc#4]
Using a Python 3.6.3 conda environment,  I used the script provided in the README to test this library out. I, however, recieve the following error:

```
Traceback (most recent call last):
  File "C:/Users/me/PycharmProjects/hitbtc/test.py", line 14, in <module>
    data = exchange.recv()
AttributeError: 'HitBTC' object has no attribute 'recv'
```

**Comment by deepbrook** [comment]
You're right - It's missing the wrapper method around the `Connector` object! Fixed this!

**Comment by alexanderborsch** [comment]
It also doesn't send the auth algo and a few more little bugs, but otherwise very useful, thanks a lot.
