### ISSUE TITLE
Client disconnects every 10 seconds

### ISSUE THREAD

**Issue by alexanderborsch** [nlsdfnbch/hitbtc#5]
Hi, here is a little bug:
The client will disconnect after 10 seconds of 'connection_timeout' and will reconnect after 10 seconds of 'reconnect_interval' as _on_message() method from WebSocketConnector is replaced in HitBTCConnector and doesn't _stop_timer(). Method _send() is overwritten too without history.append() so no re-subscription happens.

**Comment by deepbrook** [comment]
Fixed by PR #7!
