### ISSUE TITLE
Documentation misstates response item format

### ISSUE THREAD

**Issue by kjgd** [nlsdfnbch/hitbtc#9]
The documentation [states](http://hitbtc-websocket-api-20-client.readthedocs.io/en/latest/reference.html) that items on the queue are formatted as:
`(symbol, data_type, data)`

However response items are [actually returned as](https://github.com/Crypto-toolbox/hitbtc/blob/b180a8481de897dcb465c1afa14a32168527776a/hitbtc/connector.py#L156):
`('Response', 'Success', (request, response))`

Stream items are [actually returned as](https://github.com/Crypto-toolbox/hitbtc/blob/b180a8481de897dcb465c1afa14a32168527776a/hitbtc/connector.py#L176):
`(method, symbol, params)`

**Comment by deepbrook** [comment]
You are correct! Would you be willing to pick this up? I'm afraid I won't have much time this week.

**Comment by kjgd** [comment]
Done.
